// 教材カタログ（人手で選んだ定番書・公式サイト・有名学習サービス）。
// 純粋モジュール。推薦ロジック（recommend.ts）と Dify ナレッジ書き出し（scripts/dify/export_materials.mts）の元データ。
//
// 方針:
//   - 実在が確実なもの（定番書・公式サイト・公的機関・有名サービス）だけを載せる。書名・著者・URL に自信が無いものは入れない
//   - URL は公式（出版社・運営元）のみ。書籍は出版社ページが確実でなければ url を省略する
//   - levelMin/levelMax は Trivium の難易度スケール（1=誰でも、3=中学、5=高校標準、7=大学入試応用・社会人実務、9=専門家）
//   - subskills は src/lib/domain.ts の SUBSKILLS のキー
import type { Material } from "./types";

export const MATERIALS: Material[] = [
  // ------------------------------------------------------------------ READ（読解）
  {
    id: "web-nhk-news-web-easy",
    title: "NHK NEWS WEB EASY",
    kind: "web",
    author: "NHK",
    url: "https://www3.nhk.or.jp/news/easy/",
    domains: ["READ"],
    subskills: ["comprehension"],
    levelMin: 1,
    levelMax: 3,
    summary: "ニュースをやさしい日本語で書き直したサイト。ふりがな・語の説明つきで、短い文章の要点を取る練習ができる。",
    why: "長い文章がまだ苦しい人向け。毎日 1 本、「何が起きたか」を一文で言い直す練習に使える",
    free: true,
    tags: ["ニュース", "やさしい日本語", "要旨", "毎日"],
  },
  {
    id: "video-nhk-for-school",
    title: "NHK for School",
    kind: "video",
    author: "NHK",
    url: "https://www.nhk.or.jp/school/",
    domains: ["READ"],
    subskills: ["comprehension", "inference"],
    levelMin: 1,
    levelMax: 3,
    summary: "小中学生向けの教育番組・動画クリップを無料で視聴できる。国語・社会の短い動画で「話の筋」を追う練習になる。",
    why: "文章の前に、映像で「原因→結果」の流れを追うところから始めたい人向け",
    free: true,
    tags: ["動画", "国語", "入門", "無料"],
  },
  {
    id: "video-nhk-kokokoza",
    title: "NHK 高校講座",
    kind: "video",
    author: "NHK",
    url: "https://www.nhk.or.jp/kokokoza/",
    domains: ["READ"],
    subskills: ["comprehension", "inference"],
    levelMin: 3,
    levelMax: 5,
    summary: "高校の国語（現代の国語・言語文化）などを 20 分程度の番組で学べる。教科書レベルの読解を体系的に復習できる。",
    why: "高校の現代文を基礎からやり直したい人向け。1 回 20 分で、本文の構造（対比・因果）を解説つきで追える",
    free: true,
    tags: ["高校", "現代文", "動画", "無料"],
  },
  {
    id: "web-aozora-bunko",
    title: "青空文庫",
    kind: "web",
    author: "青空文庫",
    url: "https://www.aozora.gr.jp/",
    domains: ["READ"],
    subskills: ["comprehension", "inference"],
    levelMin: 3,
    levelMax: 9,
    summary: "著作権の切れた日本文学を無料で読める電子図書館。短編から評論まで、長さと難しさを自分で選べる。",
    why: "読む量を増やしたい人向け。短編（芥川・太宰など）から始めて、評論（寺田寅彦など）へ難易度を上げていける",
    free: true,
    tags: ["文学", "短編", "評論", "無料", "多読"],
  },
  {
    id: "web-nhk-news",
    title: "NHK NEWS WEB",
    kind: "web",
    author: "NHK",
    url: "https://www3.nhk.or.jp/news/",
    domains: ["READ"],
    subskills: ["comprehension", "critical_reading"],
    levelMin: 3,
    levelMax: 6,
    summary: "一般向けのニュースサイト。事実・見解・見通しを区別しながら読む練習に向く。",
    why: "「書いてあること」と「筆者の推測」を分けて読む練習をしたい人向け。1 記事 5 分",
    free: true,
    tags: ["ニュース", "時事", "事実と意見"],
  },
  {
    id: "web-kotobank",
    title: "コトバンク",
    kind: "web",
    author: "朝日新聞社・VOYAGE MARKETING",
    url: "https://kotobank.jp/",
    domains: ["READ"],
    subskills: ["comprehension"],
    levelMin: 2,
    levelMax: 7,
    summary: "複数の辞書・事典を横断検索できる無料サイト。語の意味と用例を素早く確認できる。",
    why: "語彙・表現でつまずく人向け。分からない語をその場で引き、言い換えを 1 つ覚える習慣に",
    free: true,
    tags: ["辞書", "語彙", "言い換え"],
  },
  {
    id: "web-wikipedia-ja",
    title: "Wikipedia 日本語版",
    kind: "web",
    author: "ウィキメディア財団",
    url: "https://ja.wikipedia.org/",
    domains: ["READ"],
    subskills: ["comprehension", "critical_reading"],
    levelMin: 3,
    levelMax: 7,
    summary: "百科事典。項目の冒頭要約と本文の構成を読む練習、出典の有無を確かめる練習に使える。",
    why: "「根拠が示されているか」を確かめながら読む練習をしたい人向け。脚注と出典を見る癖がつく",
    free: true,
    tags: ["事典", "出典", "批判的読解"],
  },
  {
    id: "book-todai-dokusho",
    title: "「読む力」と「地頭力」がいっきに身につく 東大読書",
    kind: "book",
    author: "西岡壱誠（東洋経済新報社）",
    domains: ["READ"],
    subskills: ["comprehension", "inference"],
    levelMin: 4,
    levelMax: 6,
    summary: "本の読み方を「仮説を立てて読む」「要約する」などの手順に分解して説明する入門書。",
    why: "本を読んでも内容が残らない人向け。読む前に問いを立てる習慣が身につく",
    free: false,
    tags: ["読書法", "要約", "入門"],
  },
  {
    id: "book-funaguchi-zero-gendaibun",
    title: "船口のゼロから読み解く最強の現代文",
    kind: "book",
    author: "船口明（学研）",
    domains: ["READ"],
    subskills: ["comprehension", "inference"],
    levelMin: 4,
    levelMax: 6,
    summary: "現代文の読み方を「文と文のつながり」から説明する受験参考書。接続の型を追って要旨をつかむ練習ができる。",
    why: "本文のどこが大事か分からない人向け。対比・因果・言い換えの目印を体系的に覚えられる",
    free: false,
    tags: ["現代文", "受験", "接続詞", "要旨"],
  },
  {
    id: "book-polaris-gendaibun-1",
    title: "大学入試 柳生好之の現代文ポラリス 1 基礎レベル",
    kind: "book",
    author: "柳生好之（KADOKAWA）",
    domains: ["READ"],
    subskills: ["comprehension", "inference"],
    levelMin: 4,
    levelMax: 6,
    summary: "現代文の読解問題を基礎から段階的に解く問題集。設問ごとに根拠の探し方が示される。",
    why: "解き方の手順を身につけたい人向け。選択肢の切り方（本文にない・言い過ぎ）を練習できる",
    free: false,
    tags: ["現代文", "問題集", "選択肢", "受験"],
  },
  {
    id: "book-shimo-gendaibun-kaihatsu",
    title: "現代文読解力の開発講座",
    kind: "book",
    author: "霜栄（駿台文庫）",
    domains: ["READ"],
    subskills: ["comprehension", "critical_reading"],
    levelMin: 6,
    levelMax: 8,
    summary: "評論文の論理構造を精読し、要約まで行う受験参考書の定番。1 題ごとの解説が厚い。",
    why: "本文の構造を自分で図にできるようになりたい人向け。要約の添削例が学べる",
    free: false,
    tags: ["現代文", "評論", "要約", "精読"],
  },
  {
    id: "book-chikuma-hyoron-nyumon",
    title: "ちくま評論入門",
    kind: "book",
    author: "筑摩書房編集部 編（筑摩書房）",
    domains: ["READ"],
    subskills: ["comprehension", "critical_reading"],
    levelMin: 6,
    levelMax: 8,
    summary: "高校生向けの評論アンソロジー。抽象的な語を含む文章を、設問と解説つきで読める。",
    why: "評論の語彙と論の運びに慣れたい人向け。1 編ずつ要旨をノートにまとめるのに向く",
    free: false,
    tags: ["評論", "アンソロジー", "高校"],
  },
  {
    id: "book-chikuma-bunsho-dokuhon",
    title: "高校生のための文章読本",
    kind: "book",
    author: "梅田卓夫ほか 編（筑摩書房）",
    domains: ["READ", "WRITE"],
    subskills: ["comprehension", "clarity"],
    levelMin: 5,
    levelMax: 7,
    summary: "多様なジャンルの名文を集めた読本。読む力と書く力の両方の手本になる。",
    why: "良い文章の「型」を体で覚えたい人向け。気に入った一段落を書き写す練習に",
    free: false,
    tags: ["名文", "文章", "高校", "書き写し"],
  },
  {
    id: "book-chiteki-fukugan",
    title: "知的複眼思考法",
    kind: "book",
    author: "苅谷剛彦（講談社+α文庫）",
    domains: ["READ", "WRITE"],
    subskills: ["critical_reading", "reasoning"],
    levelMin: 6,
    levelMax: 8,
    summary: "「常識を疑って問いを立てる」方法を、読む・書く・考えるの面から説く定番書。",
    why: "書いてあることを鵜呑みにしがちな人向け。前提を疑う問いの立て方が具体的に分かる",
    free: false,
    tags: ["批判的思考", "問い", "大学"],
  },
  {
    id: "book-shiko-no-seirigaku",
    title: "思考の整理学",
    kind: "book",
    author: "外山滋比古（ちくま文庫）",
    domains: ["READ", "WRITE"],
    subskills: ["inference", "structure"],
    levelMin: 5,
    levelMax: 7,
    summary: "考えを寝かせる・組み合わせる・書いて整理する、といった知的作業の方法を軽快に説くエッセイ。",
    why: "読んだことを自分の考えに変えるのが苦手な人向け。短い章で読みやすい",
    free: false,
    tags: ["思考法", "エッセイ", "大学"],
  },
  {
    id: "book-wakaru-toha",
    title: "「わかる」とはどういうことか",
    kind: "book",
    author: "山鳥重（ちくま新書）",
    domains: ["READ"],
    subskills: ["inference", "critical_reading"],
    levelMin: 6,
    levelMax: 8,
    summary: "「わかる」という体験を認知の面から解きほぐす新書。理解の段階を意識して読む助けになる。",
    why: "読めているつもりで説明できない人向け。「わかったつもり」の正体が分かる",
    free: false,
    tags: ["認知", "理解", "新書"],
  },
  {
    id: "book-nihongo-renshucho",
    title: "日本語練習帳",
    kind: "book",
    author: "大野晋（岩波新書）",
    domains: ["READ", "WRITE"],
    subskills: ["comprehension", "clarity"],
    levelMin: 5,
    levelMax: 7,
    summary: "「は」と「が」の違いなど、日本語の感覚を練習問題で磨く名著。読み書き両方の精度が上がる。",
    why: "一文一文を正確に読み、書きたい人向け。短い練習問題を毎日 1 つ",
    free: false,
    tags: ["日本語", "文法", "練習問題", "新書"],
  },
  {
    id: "book-critical-thinking-nyumon",
    title: "クリティカルシンキング 入門篇",
    kind: "book",
    author: "E.B.ゼックミスタ・J.E.ジョンソン（北大路書房）",
    domains: ["READ"],
    subskills: ["critical_reading", "inference"],
    levelMin: 7,
    levelMax: 9,
    summary: "主張と根拠の評価、誤った推論のパターンを体系的に学ぶ教科書。演習問題つき。",
    why: "議論の弱点を指摘できるようになりたい人向け。大学の教科書として使われる",
    free: false,
    tags: ["批判的思考", "推論", "教科書", "大学"],
  },
  {
    id: "book-tetsugaku-shiko-training",
    title: "哲学思考トレーニング",
    kind: "book",
    author: "伊勢田哲治（ちくま新書）",
    domains: ["READ", "CODE"],
    subskills: ["critical_reading", "design"],
    levelMin: 6,
    levelMax: 8,
    summary: "議論を評価するための道具（論証の構造、反例、疑似科学の見分け方）を新書サイズで解説。",
    why: "「なんとなく変だ」を言葉にしたい人向け。批判的読解と論理の橋渡しになる",
    free: false,
    tags: ["哲学", "論証", "批判的思考", "新書"],
  },
  {
    id: "book-33-shiko-jikken",
    title: "論理的思考力を鍛える 33 の思考実験",
    kind: "book",
    author: "北村良子（彩図社）",
    domains: ["READ", "CODE"],
    subskills: ["inference", "design"],
    levelMin: 4,
    levelMax: 6,
    summary: "トロッコ問題などの思考実験を通じて、前提と結論の関係を考える入門書。",
    why: "堅い教科書より読み物から入りたい人向け。1 題 10 分で議論の練習ができる",
    free: false,
    tags: ["思考実験", "読み物", "入門"],
  },

  // ------------------------------------------------------------------ WRITE（作文・文章術）
  {
    id: "book-bunshoryoku-no-kihon",
    title: "文章力の基本",
    kind: "book",
    author: "阿部紘久（日本実業出版社）",
    domains: ["WRITE"],
    subskills: ["clarity", "revision"],
    levelMin: 3,
    levelMax: 5,
    summary: "「一文を短く」「主語と述語を近づける」など、分かりやすい文の基本 77 項目を例文で示す。",
    why: "文が長くなる・ねじれる人向け。推敲のチェックリストとして使える",
    free: false,
    tags: ["文章術", "推敲", "基本", "例文"],
  },
  {
    id: "book-atarashii-bunshoryoku",
    title: "新しい文章力の教室",
    kind: "book",
    author: "唐木元（インプレス）",
    domains: ["WRITE"],
    subskills: ["structure", "clarity"],
    levelMin: 4,
    levelMax: 6,
    summary: "書く前に「構造シート」で要素を並べてから書く方法を、Web 編集の現場の知見で説く。",
    why: "書き始めると止まる人向け。「先に材料を並べる」だけで完成率が上がる",
    free: false,
    tags: ["文章術", "構成", "Web", "編集"],
  },
  {
    id: "book-20sai-bunsho-kogi",
    title: "20 歳の自分に受けさせたい文章講義",
    kind: "book",
    author: "古賀史健（星海社新書）",
    domains: ["WRITE"],
    subskills: ["structure", "reasoning"],
    levelMin: 4,
    levelMax: 7,
    summary: "「話せるのに書けない」を出発点に、読者を想定して論理的に書く方法を講義形式で説明。",
    why: "頭の中の考えを文章にできない人向け。文章のリズムと論理の両方を扱う",
    free: false,
    tags: ["文章術", "読者", "論理", "新書"],
  },
  {
    id: "book-tsutawaru-yusaburu",
    title: "伝わる・揺さぶる！文章を書く",
    kind: "book",
    author: "山田ズーニー（PHP 新書）",
    domains: ["WRITE"],
    subskills: ["reasoning", "structure"],
    levelMin: 4,
    levelMax: 6,
    summary: "「問い」を立て、根拠を並べ、相手を動かす文章の作り方を 7 つの要件で説明する。",
    why: "意見文で理由が浅くなる人向け。「なぜそう言えるか」を掘る練習ができる",
    free: false,
    tags: ["意見文", "根拠", "説得", "新書"],
  },
  {
    id: "book-shoronbun-koredake",
    title: "小論文これだけ！ 超基礎編",
    kind: "book",
    author: "樋口裕一（東洋経済新報社）",
    domains: ["WRITE"],
    subskills: ["structure", "reasoning"],
    levelMin: 3,
    levelMax: 5,
    summary: "小論文の型（問題提起→意見→根拠→結論）を最小限の手順で身につける入門書。",
    why: "型がまだ無い人向け。まず 1 つの型で書き切る練習に",
    free: false,
    tags: ["小論文", "型", "入門", "受験"],
  },
  {
    id: "book-rikakei-sakubun",
    title: "理科系の作文技術",
    kind: "book",
    author: "木下是雄（中公新書）",
    domains: ["WRITE"],
    subskills: ["clarity", "structure"],
    levelMin: 6,
    levelMax: 8,
    summary: "事実と意見を分け、明快な文を書くための古典。パラグラフ・目的規定文・読み返しの原則。",
    why: "レポートや報告書を書く人向け。「一義的に読める文」の基準が分かる",
    free: false,
    tags: ["レポート", "パラグラフ", "明確さ", "新書", "定番"],
  },
  {
    id: "book-nihongo-no-sakubun-gijutsu",
    title: "日本語の作文技術",
    kind: "book",
    author: "本多勝一（朝日文庫）",
    domains: ["WRITE"],
    subskills: ["clarity", "revision"],
    levelMin: 5,
    levelMax: 8,
    summary: "修飾語の順序・読点の打ち方など、日本語で誤読を防ぐ技術を具体例で示す定番書。",
    why: "読みにくいと言われるが理由が分からない人向け。語順と読点の規則が明快",
    free: false,
    tags: ["語順", "読点", "推敲", "定番"],
  },
  {
    id: "book-cho-bunshoho",
    title: "「超」文章法",
    kind: "book",
    author: "野口悠紀雄（中公新書）",
    domains: ["WRITE"],
    subskills: ["structure", "reasoning"],
    levelMin: 6,
    levelMax: 8,
    summary: "「メッセージを 1 つに絞る」ことを軸に、骨組み→肉付け→推敲の順で長い文章を組み立てる方法。",
    why: "長い文章の全体構成に悩む人向け。骨組みの作り方が具体的",
    free: false,
    tags: ["構成", "長文", "メッセージ", "新書"],
  },
  {
    id: "book-ronri-ga-tsutawaru-kaku-gijutsu",
    title: "論理が伝わる 世界標準の「書く技術」",
    kind: "book",
    author: "倉島保美（講談社ブルーバックス）",
    domains: ["WRITE"],
    subskills: ["structure", "clarity"],
    levelMin: 6,
    levelMax: 8,
    summary: "パラグラフ・ライティングの原則（1 段落 1 トピック、先頭に要約文）を日本語で実践する方法。",
    why: "段落の役割が曖昧になる人向け。英語圏の技術文書の型が身につく",
    free: false,
    tags: ["パラグラフ", "技術文書", "構成"],
  },
  {
    id: "book-nyumon-kangaeru-gijutsu",
    title: "入門 考える技術・書く技術",
    kind: "book",
    author: "山崎康司（ダイヤモンド社）",
    domains: ["WRITE"],
    subskills: ["structure", "reasoning"],
    levelMin: 5,
    levelMax: 7,
    summary: "ピラミッド原則（結論→根拠の階層）を日本のビジネス文書向けに噛み砕いた入門書。",
    why: "結論が最後にしか出てこない人向け。「結論を先に」を型として練習できる",
    free: false,
    tags: ["ピラミッド原則", "ビジネス文書", "結論先出し"],
  },
  {
    id: "book-kangaeru-gijutsu-kaku-gijutsu",
    title: "考える技術・書く技術",
    kind: "book",
    author: "バーバラ・ミント（ダイヤモンド社）",
    domains: ["WRITE"],
    subskills: ["structure", "reasoning"],
    levelMin: 7,
    levelMax: 9,
    summary: "ピラミッド原則の原典。論理の階層を組み、疑問に答える順で書く方法を徹底的に説明。",
    why: "報告書や提案書で論理の穴を指摘される人向け。読み応えはあるが効果は大きい",
    free: false,
    tags: ["ピラミッド原則", "論理", "ビジネス", "定番"],
  },
  {
    id: "book-logical-thinking",
    title: "ロジカル・シンキング",
    kind: "book",
    author: "照屋華子・岡田恵子（東洋経済新報社）",
    domains: ["WRITE"],
    subskills: ["reasoning", "structure"],
    levelMin: 6,
    levelMax: 8,
    summary: "MECE や So What?／Why So? など、根拠と結論のつながりを点検する道具を紹介する定番書。",
    why: "「根拠が結論を支えているか」を自分で点検したい人向け",
    free: false,
    tags: ["MECE", "根拠", "ビジネス", "定番"],
  },
  {
    id: "book-giron-no-lesson",
    title: "新版 議論のレッスン",
    kind: "book",
    author: "福澤一吉（NHK 出版新書）",
    domains: ["WRITE", "READ"],
    subskills: ["reasoning", "critical_reading"],
    levelMin: 6,
    levelMax: 8,
    summary: "主張・根拠・論拠（暗黙の前提）を分けて議論を組み立てる方法。反論の型も学べる。",
    why: "反対意見への応答が書けない人向け。「論拠」を意識すると反論が書けるようになる",
    free: false,
    tags: ["議論", "論拠", "反論", "新書"],
  },
  {
    id: "book-ronbun-no-kyoshitsu",
    title: "新版 論文の教室",
    kind: "book",
    author: "戸田山和久（NHK ブックス）",
    domains: ["WRITE"],
    subskills: ["structure", "reasoning", "revision"],
    levelMin: 7,
    levelMax: 9,
    summary: "問いの立て方からアウトライン、推敲までを、ダメな例と良い例の対比で示す論文入門の定番。",
    why: "レポートが「感想文」になる人向け。問いと主張と根拠の関係が身につく",
    free: false,
    tags: ["論文", "レポート", "アウトライン", "定番"],
  },
  {
    id: "book-daigakusei-report-ronbun",
    title: "新版 大学生のためのレポート・論文術",
    kind: "book",
    author: "小笠原喜康（講談社現代新書）",
    domains: ["WRITE"],
    subskills: ["structure", "revision"],
    levelMin: 6,
    levelMax: 8,
    summary: "レポートの形式・引用・構成を実務的に説明する新書。書式の疑問に答える。",
    why: "形式や引用の作法で迷う人向け。手元に置く参考書として",
    free: false,
    tags: ["レポート", "引用", "書式", "新書"],
  },
  {
    id: "book-issue-kara-hajimeyo",
    title: "イシューからはじめよ",
    kind: "book",
    author: "安宅和人（英治出版）",
    domains: ["WRITE", "CODE"],
    subskills: ["reasoning", "design"],
    levelMin: 7,
    levelMax: 9,
    summary: "「解くべき問い（イシュー）」を見極めてから分析・伝達に進む方法。ストーリーラインの組み方も扱う。",
    why: "頑張っているのに伝わらない人向け。問いの設定から見直す視点が得られる",
    free: false,
    tags: ["問題設定", "ストーリーライン", "ビジネス"],
  },
  {
    id: "book-sekaiichi-yasashii-mondai-kaiketsu",
    title: "世界一やさしい問題解決の授業",
    kind: "book",
    author: "渡辺健介（ダイヤモンド社）",
    domains: ["WRITE", "CODE"],
    subskills: ["reasoning", "design"],
    levelMin: 3,
    levelMax: 5,
    summary: "中高生向けに、原因の分解（ロジックツリー）と仮説→検証の流れを物語で教える入門書。",
    why: "理由を 1 つしか思いつかない人向け。分解して考える最初の一冊",
    free: false,
    tags: ["問題解決", "ロジックツリー", "入門", "中高生"],
  },
  {
    id: "book-bunsho-dokuhon-tanizaki",
    title: "文章読本",
    kind: "book",
    author: "谷崎潤一郎（中公文庫）",
    domains: ["WRITE"],
    subskills: ["clarity", "revision"],
    levelMin: 6,
    levelMax: 8,
    summary: "文豪による文章論の古典。「分かりやすさ」と「感覚」の両面から日本語の文体を論じる。",
    why: "正確さの先に、読み心地まで意識したい人向け",
    free: false,
    tags: ["文体", "古典", "文章論"],
  },
  {
    id: "book-rhetoric-kankaku",
    title: "レトリック感覚",
    kind: "book",
    author: "佐藤信夫（講談社学術文庫）",
    domains: ["WRITE", "READ"],
    subskills: ["clarity", "inference"],
    levelMin: 7,
    levelMax: 9,
    summary: "直喩・隠喩・換喩などの表現技法を、言葉の「発見」の働きとして解説する名著。",
    why: "表現の幅を広げたい人、比喩の効果を読み取りたい人向け",
    free: false,
    tags: ["レトリック", "比喩", "表現"],
  },

  // ------------------------------------------------------------------ LOGIC（Python）
  {
    id: "course-progate",
    title: "Progate",
    kind: "course",
    author: "Progate",
    url: "https://prog-8.com/",
    domains: ["CODE"],
    subskills: ["tracing"],
    levelMin: 1,
    levelMax: 4,
    summary: "ブラウザ上でスライドと演習を交互に進めるプログラミング学習サービス。Python コースあり（一部無料）。",
    why: "環境構築なしで今日から始めたい人向け。最初の「動いた」を短時間で体験できる",
    free: false,
    tags: ["Python", "入門", "ブラウザ", "演習"],
  },
  {
    id: "course-dotinstall",
    title: "ドットインストール",
    kind: "course",
    author: "ドットインストール",
    url: "https://dotinstall.com/",
    domains: ["CODE"],
    subskills: ["tracing"],
    levelMin: 1,
    levelMax: 4,
    summary: "3 分動画でプログラミングを学ぶサービス。Python 入門レッスンあり（一部無料）。",
    why: "短い動画で少しずつ進めたい人向け。通勤時間の 3 分に",
    free: false,
    tags: ["Python", "動画", "入門", "3分"],
  },
  {
    id: "course-paiza-learning",
    title: "paiza ラーニング",
    kind: "course",
    author: "paiza",
    url: "https://paiza.jp/works",
    domains: ["CODE"],
    subskills: ["tracing", "algorithms"],
    levelMin: 1,
    levelMax: 5,
    summary: "動画＋ブラウザ演習で Python などを学べる。入門から標準入力・アルゴリズム基礎まで（一部無料）。",
    why: "見て終わりにならず、その場で書いて確かめたい人向け",
    free: false,
    tags: ["Python", "動画", "演習", "標準入力"],
  },
  {
    id: "book-python-1nensei",
    title: "Python 1 年生 体験してわかる！会話でまなべる！プログラミングのしくみ",
    kind: "book",
    author: "森巧尚（翔泳社）",
    domains: ["CODE"],
    subskills: ["tracing"],
    levelMin: 1,
    levelMax: 3,
    summary: "対話形式のイラスト入門書。変数・条件分岐・繰り返しを小さなプログラムで体験する。",
    why: "プログラミングが初めてで、まず怖さをなくしたい人向け",
    free: false,
    tags: ["Python", "入門", "イラスト", "初めて"],
  },
  {
    id: "book-sukkiri-python",
    title: "スッキリわかる Python 入門",
    kind: "book",
    author: "国本大悟・須藤秋良（インプレス）",
    domains: ["CODE"],
    subskills: ["tracing", "debugging"],
    levelMin: 2,
    levelMax: 4,
    summary: "基本文法を「なぜそう書くか」まで丁寧に説明する入門書。エラーの読み方の章がある。",
    why: "エラーが出ると止まってしまう人向け。エラーメッセージを読む練習になる",
    free: false,
    tags: ["Python", "入門", "エラー", "文法"],
  },
  {
    id: "book-minna-no-python",
    title: "みんなの Python 第 4 版",
    kind: "book",
    author: "柴田淳（SB クリエイティブ）",
    domains: ["CODE"],
    subskills: ["tracing", "design"],
    levelMin: 3,
    levelMax: 6,
    summary: "文法から標準ライブラリ、オブジェクト指向まで体系的に学べる定番の入門書。",
    why: "断片的な知識をつなげたい人向け。辞書のように引き直せる",
    free: false,
    tags: ["Python", "定番", "体系", "標準ライブラリ"],
  },
  {
    id: "book-dokugaku-programmer",
    title: "独学プログラマー Python 言語の基本から仕事のやり方まで",
    kind: "book",
    author: "コーリー・アルソフ（日経 BP）",
    domains: ["CODE"],
    subskills: ["tracing", "design"],
    levelMin: 2,
    levelMax: 5,
    summary: "Python の基礎に加えて、Git・作法・問題の分け方など「プログラマの仕事」まで扱う。",
    why: "文法の次に何をすればいいか分からない人向け",
    free: false,
    tags: ["Python", "独学", "実務", "Git"],
  },
  {
    id: "book-automate-boring-stuff",
    title: "退屈なことは Python にやらせよう 第 2 版",
    kind: "book",
    author: "Al Sweigart（オライリー・ジャパン）",
    domains: ["CODE"],
    subskills: ["tracing", "design"],
    levelMin: 3,
    levelMax: 6,
    summary: "ファイル整理・Excel・Web など身近な作業を Python で自動化しながら学ぶ実践入門。",
    why: "目的があったほうが続く人向け。自分の作業を 1 つ自動化する題材に",
    free: false,
    tags: ["Python", "自動化", "実践", "オライリー"],
  },
  {
    id: "web-automate-boring-stuff-online",
    title: "Automate the Boring Stuff with Python（オンライン版）",
    kind: "web",
    author: "Al Sweigart",
    url: "https://automatetheboringstuff.com/",
    domains: ["CODE"],
    subskills: ["tracing", "design"],
    levelMin: 3,
    levelMax: 6,
    summary: "上記書籍の英語原文を無料で読めるサイト。章ごとに練習課題がある。",
    why: "英語でも読める人向け。無料で全章が読める",
    free: true,
    tags: ["Python", "英語", "無料", "自動化"],
    language: "en",
  },
  {
    id: "web-python-tutorial-ja",
    title: "Python チュートリアル（公式・日本語）",
    kind: "web",
    author: "Python Software Foundation",
    url: "https://docs.python.org/ja/3/tutorial/",
    domains: ["CODE"],
    subskills: ["tracing", "design"],
    levelMin: 3,
    levelMax: 6,
    summary: "Python 公式のチュートリアル日本語訳。言語の基本を正確に、公式の説明で学べる。",
    why: "書籍の説明が本当か確かめたい人、正確な仕様を知りたい人向け。無料",
    free: true,
    tags: ["Python", "公式", "無料", "仕様"],
  },
  {
    id: "book-python-tutorial-oreilly",
    title: "Python チュートリアル 第 4 版",
    kind: "book",
    author: "Guido van Rossum（オライリー・ジャパン）",
    domains: ["CODE"],
    subskills: ["tracing", "design"],
    levelMin: 4,
    levelMax: 6,
    summary: "Python 作者による公式チュートリアルの書籍版。要点が簡潔にまとまっている。",
    why: "薄い本で言語の全体像をつかみたい人向け",
    free: false,
    tags: ["Python", "公式", "簡潔"],
  },
  {
    id: "book-nyumon-python3",
    title: "入門 Python 3 第 2 版",
    kind: "book",
    author: "Bill Lubanovic（オライリー・ジャパン）",
    domains: ["CODE"],
    subskills: ["tracing", "design"],
    levelMin: 4,
    levelMax: 7,
    summary: "文法から実務的なトピック（データ、Web、並行処理）まで幅広く扱う中級向けの定番。",
    why: "入門を終えて次の一冊を探している人向け。分厚いが辞書的に使える",
    free: false,
    tags: ["Python", "中級", "オライリー", "定番"],
  },
  {
    id: "web-python-tutor",
    title: "Python Tutor",
    kind: "web",
    author: "Philip Guo",
    url: "https://pythontutor.com/",
    domains: ["CODE"],
    subskills: ["tracing", "debugging"],
    levelMin: 2,
    levelMax: 6,
    summary: "コードを 1 行ずつ実行して変数やリストの中身を図で見られる無料ツール。",
    why: "頭の中で値を追うのが苦手な人向け。Trivium の「出力予測」で迷った問題を貼って動かすと理解が速い",
    free: true,
    tags: ["Python", "可視化", "トレース", "無料", "デバッグ"],
    language: "en",
  },
  {
    id: "web-google-colab",
    title: "Google Colaboratory",
    kind: "web",
    author: "Google",
    url: "https://colab.research.google.com/",
    domains: ["CODE"],
    subskills: ["tracing", "debugging"],
    levelMin: 2,
    levelMax: 8,
    summary: "ブラウザで Python を実行できるノートブック環境。環境構築なしで試せる。",
    why: "PC に Python を入れずに、読んだコードをすぐ実行して確かめたい人向け",
    free: true,
    tags: ["Python", "実行環境", "ノートブック", "無料"],
  },
  {
    id: "video-kinocode",
    title: "キノコード / プログラミング学習チャンネル（YouTube）",
    kind: "video",
    author: "キノコード",
    url: "https://www.youtube.com/@kinocode",
    domains: ["CODE"],
    subskills: ["tracing"],
    levelMin: 2,
    levelMax: 5,
    summary: "Python 入門を中心に、文法や自動化を動画で丁寧に解説する日本語チャンネル。",
    why: "本より動画のほうが頭に入る人向け。入門シリーズを順番に",
    free: true,
    tags: ["Python", "動画", "YouTube", "無料"],
  },
  {
    id: "course-google-python-class",
    title: "Google's Python Class",
    kind: "course",
    author: "Google for Education",
    url: "https://developers.google.com/edu/python",
    domains: ["CODE"],
    subskills: ["tracing", "algorithms"],
    levelMin: 4,
    levelMax: 6,
    summary: "Google が公開している Python の無料講座。講義ノートと練習問題（文字列・リスト・正規表現）。",
    why: "英語の演習で手を動かしたい人向け。練習問題の質が高い",
    free: true,
    tags: ["Python", "英語", "演習", "無料"],
    language: "en",
  },
  {
    id: "web-real-python",
    title: "Real Python",
    kind: "web",
    author: "Real Python",
    url: "https://realpython.com/",
    domains: ["CODE"],
    subskills: ["design", "tracing"],
    levelMin: 4,
    levelMax: 8,
    summary: "Python の各トピックを深掘りする英語の解説記事サイト（一部無料）。",
    why: "特定の機能（デコレータ・ジェネレータなど）を腰を据えて理解したい人向け",
    free: false,
    tags: ["Python", "英語", "解説", "中級"],
    language: "en",
  },
  {
    id: "book-readable-code",
    title: "リーダブルコード",
    kind: "book",
    author: "Dustin Boswell・Trevor Foucher（オライリー・ジャパン）",
    domains: ["CODE", "WRITE"],
    subskills: ["design", "clarity"],
    levelMin: 5,
    levelMax: 8,
    summary: "読みやすいコードの書き方（命名・コメント・制御の流れ）を短い例で示す定番書。",
    why: "動くが読みにくいと言われる人向け。文章の「明確さ」と同じ考え方が学べる",
    free: false,
    tags: ["コード品質", "命名", "定番", "設計"],
  },
  {
    id: "book-program-wa-naze-ugoku",
    title: "プログラムはなぜ動くのか 第 3 版",
    kind: "book",
    author: "矢沢久雄（日経 BP）",
    domains: ["CODE"],
    subskills: ["design", "tracing"],
    levelMin: 4,
    levelMax: 7,
    summary: "CPU・メモリ・実行の仕組みを、プログラムが動く原理から説明する定番書。",
    why: "コードの裏で何が起きているか知りたい人向け",
    free: false,
    tags: ["コンピュータの仕組み", "CPU", "定番"],
  },

  // ------------------------------------------------------------------ LOGIC（アルゴリズム・競技プログラミング）
  {
    id: "book-algorithm-zukan",
    title: "アルゴリズム図鑑 増補改訂版",
    kind: "book",
    author: "石田保輝・宮崎修一（翔泳社）",
    domains: ["CODE"],
    subskills: ["algorithms"],
    levelMin: 3,
    levelMax: 6,
    summary: "ソート・探索・グラフなどの基本アルゴリズムを、図だけで手順を追える形で解説。",
    why: "コードを書く前に手順を絵で理解したい人向け。「手順・アルゴリズム」問題の予習に",
    free: false,
    tags: ["アルゴリズム", "図解", "入門", "ソート"],
  },
  {
    id: "book-9-algorithms",
    title: "世界でもっとも強力な 9 のアルゴリズム",
    kind: "book",
    author: "ジョン・マコーミック（日経 BP）",
    domains: ["CODE", "READ"],
    subskills: ["algorithms", "comprehension"],
    levelMin: 4,
    levelMax: 7,
    summary: "検索・圧縮・暗号などの重要アルゴリズムを、数式を使わずに読み物として解説。",
    why: "アルゴリズムの「何がすごいのか」を先に知りたい人向け",
    free: false,
    tags: ["アルゴリズム", "読み物", "教養"],
  },
  {
    id: "book-python-algorithm-nyumon",
    title: "Python ではじめるアルゴリズム入門",
    kind: "book",
    author: "増井敏克（翔泳社）",
    domains: ["CODE"],
    subskills: ["algorithms", "tracing"],
    levelMin: 4,
    levelMax: 7,
    summary: "探索・ソート・再帰・動的計画法を Python のコードで実装しながら学ぶ入門書。",
    why: "Python は書けるがアルゴリズムは初めての人向け",
    free: false,
    tags: ["Python", "アルゴリズム", "再帰", "動的計画法"],
  },
  {
    id: "book-mondai-kaiketsu-algorithm",
    title: "問題解決力を鍛える！アルゴリズムとデータ構造",
    kind: "book",
    author: "大槻兼資（講談社）",
    domains: ["CODE"],
    subskills: ["algorithms", "design"],
    levelMin: 6,
    levelMax: 9,
    summary: "設計技法（全探索・動的計画法・二分探索・グラフ）を「問題をどう捉えるか」から説明する本格的な教科書。",
    why: "Trivium の LOGIC で難易度 7 以上を目指す人向け。章末問題が豊富",
    free: false,
    tags: ["アルゴリズム", "データ構造", "教科書", "競技プログラミング"],
  },
  {
    id: "book-programming-contest-algorithm",
    title: "プログラミングコンテスト攻略のためのアルゴリズムとデータ構造",
    kind: "book",
    author: "渡部有隆（マイナビ出版）",
    domains: ["CODE"],
    subskills: ["algorithms", "tracing"],
    levelMin: 6,
    levelMax: 9,
    summary: "AIZU ONLINE JUDGE の問題と対応した、実装しながら学ぶアルゴリズムの定番書。",
    why: "読むだけでなくジャッジで正解を確かめながら進めたい人向け",
    free: false,
    tags: ["アルゴリズム", "競技プログラミング", "AOJ"],
  },
  {
    id: "book-kyopro-tessoku",
    title: "競技プログラミングの鉄則",
    kind: "book",
    author: "米田優峻（マイナビ出版）",
    domains: ["CODE"],
    subskills: ["algorithms", "design"],
    levelMin: 5,
    levelMax: 9,
    summary: "競技プログラミングの典型手法を段階的に学ぶ入門〜中級書。演習問題は AtCoder で提出できる。",
    why: "AtCoder を始めたが伸び悩む人向け。典型パターンを体系的に",
    free: false,
    tags: ["競技プログラミング", "AtCoder", "典型"],
  },
  {
    id: "practice-atcoder-beginners-selection",
    title: "AtCoder Beginners Selection",
    kind: "practice",
    author: "AtCoder",
    url: "https://atcoder.jp/contests/abs",
    domains: ["CODE"],
    subskills: ["tracing", "algorithms"],
    levelMin: 3,
    levelMax: 6,
    summary: "AtCoder が用意した入門用の 10 問。標準入力・ループ・条件分岐の基本を確かめられる。",
    why: "競技プログラミングの最初の 10 問として。Python で提出できる",
    free: true,
    tags: ["競技プログラミング", "AtCoder", "入門", "無料"],
  },
  {
    id: "practice-atcoder",
    title: "AtCoder",
    kind: "practice",
    author: "AtCoder",
    url: "https://atcoder.jp/",
    domains: ["CODE"],
    subskills: ["algorithms", "design"],
    levelMin: 5,
    levelMax: 10,
    summary: "毎週コンテストが開かれる競技プログラミングサイト。過去問は常時解ける。",
    why: "解けたかどうかが即座に分かる環境で力を測りたい人向け。ABC の A〜C 問題から",
    free: true,
    tags: ["競技プログラミング", "コンテスト", "無料"],
  },
  {
    id: "practice-atcoder-problems",
    title: "AtCoder Problems",
    kind: "practice",
    author: "kenkoooo",
    url: "https://kenkoooo.com/atcoder/",
    domains: ["CODE"],
    subskills: ["algorithms"],
    levelMin: 5,
    levelMax: 10,
    summary: "AtCoder の過去問を難易度順に並べ、解いた問題を管理できる有名な非公式サイト。",
    why: "自分の難易度に合った問題を順に解きたい人向け。Trivium のレベルと同じ発想",
    free: true,
    tags: ["競技プログラミング", "過去問", "難易度順"],
  },
  {
    id: "practice-atcoder-typical90",
    title: "競プロ典型 90 問",
    kind: "practice",
    author: "E869120（AtCoder）",
    url: "https://atcoder.jp/contests/typical90",
    domains: ["CODE"],
    subskills: ["algorithms", "design"],
    levelMin: 7,
    levelMax: 10,
    summary: "競技プログラミングの典型手法を 90 問で網羅する常設コンテスト。難易度が星で示される。",
    why: "LOGIC 難易度 8 以上に挑みたい人向け。星 2〜3 から順に",
    free: true,
    tags: ["競技プログラミング", "典型", "上級"],
  },
  {
    id: "practice-aoj",
    title: "AIZU ONLINE JUDGE",
    kind: "practice",
    author: "会津大学",
    url: "https://onlinejudge.u-aizu.ac.jp/",
    domains: ["CODE"],
    subskills: ["algorithms", "tracing"],
    levelMin: 4,
    levelMax: 9,
    summary: "会津大学が運営するオンラインジャッジ。入門コースからアルゴリズムの体系的なコースまで。",
    why: "教科書の順に、ジャッジで確かめながら進めたい人向け",
    free: true,
    tags: ["競技プログラミング", "ジャッジ", "コース", "無料"],
  },
  {
    id: "practice-paiza-skill-check",
    title: "paiza スキルチェック",
    kind: "practice",
    author: "paiza",
    url: "https://paiza.jp/challenges",
    domains: ["CODE"],
    subskills: ["algorithms", "tracing"],
    levelMin: 3,
    levelMax: 8,
    summary: "D〜S ランクの問題を解いてスキルを測るサービス。標準入力の扱いから学べる。",
    why: "自分の実力をランクで知りたい人向け。D・C ランクから",
    free: true,
    tags: ["ランク", "標準入力", "演習"],
  },
  {
    id: "practice-project-euler",
    title: "Project Euler",
    kind: "practice",
    author: "Project Euler",
    url: "https://projecteuler.net/",
    domains: ["CODE"],
    subskills: ["algorithms", "design"],
    levelMin: 6,
    levelMax: 10,
    summary: "数学とプログラミングを組み合わせた問題集。答えは数値 1 つで、言語は自由。",
    why: "数的推理とアルゴリズムを同時に鍛えたい人向け。最初の 20 問は Python で十分",
    free: true,
    tags: ["数学", "アルゴリズム", "英語", "無料"],
    language: "en",
  },
  {
    id: "practice-leetcode",
    title: "LeetCode",
    kind: "practice",
    author: "LeetCode",
    url: "https://leetcode.com/",
    domains: ["CODE"],
    subskills: ["algorithms", "design"],
    levelMin: 5,
    levelMax: 9,
    summary: "アルゴリズム問題の英語サイト。Easy から順に、関数を実装する形式で解く。",
    why: "面接対策や英語圏の定番問題に触れたい人向け",
    free: false,
    tags: ["アルゴリズム", "英語", "面接"],
    language: "en",
  },
  {
    id: "practice-codewars",
    title: "Codewars",
    kind: "practice",
    author: "Codewars",
    url: "https://www.codewars.com/",
    domains: ["CODE"],
    subskills: ["tracing", "design"],
    levelMin: 4,
    levelMax: 8,
    summary: "小さな関数を実装する問題（kata）を難易度別に解ける英語サイト。他人の解答も読める。",
    why: "短い問題を数多く、他人のコードと比べながら解きたい人向け",
    free: true,
    tags: ["演習", "英語", "他人の解答"],
    language: "en",
  },
  {
    id: "practice-codeforces",
    title: "Codeforces",
    kind: "practice",
    author: "Codeforces",
    url: "https://codeforces.com/",
    domains: ["CODE"],
    subskills: ["algorithms", "design"],
    levelMin: 7,
    levelMax: 10,
    summary: "世界規模の競技プログラミングサイト。レーティング制で難問が多い。",
    why: "AtCoder の上位を狙う人向け。上級者の練習場",
    free: true,
    tags: ["競技プログラミング", "上級", "英語"],
    language: "en",
  },

  // ------------------------------------------------------------------ LOGIC（論理・数的推理・パズル）
  {
    id: "book-nyumon-ronrigaku",
    title: "入門！論理学",
    kind: "book",
    author: "野矢茂樹（中公新書）",
    domains: ["CODE", "READ"],
    subskills: ["design", "critical_reading"],
    levelMin: 5,
    levelMax: 7,
    summary: "否定・かつ・または・ならば、対偶や背理法を、日常の例で語りかけるように説明する入門書。",
    why: "「対偶」「必要条件と十分条件」で迷う人向け。Trivium の論理パズルの土台になる",
    free: false,
    tags: ["論理学", "対偶", "入門", "新書"],
  },
  {
    id: "book-ronri-training-101",
    title: "論理トレーニング 101 題",
    kind: "book",
    author: "野矢茂樹（産業図書）",
    domains: ["READ", "WRITE", "CODE"],
    subskills: ["critical_reading", "reasoning", "design"],
    levelMin: 5,
    levelMax: 8,
    summary: "接続の分析・論証の評価を 101 題の演習で鍛える定番。読む・書く・論理の三つに効く。",
    why: "Trivium の 3 系統をまとめて底上げしたい人向け。1 日 3 題ずつ",
    free: false,
    tags: ["論理", "演習", "接続詞", "論証", "定番"],
  },
  {
    id: "book-shinpan-ronri-training",
    title: "新版 論理トレーニング",
    kind: "book",
    author: "野矢茂樹（産業図書）",
    domains: ["READ", "WRITE"],
    subskills: ["critical_reading", "reasoning"],
    levelMin: 6,
    levelMax: 9,
    summary: "『101 題』の理論編。議論の構造・論証・批判の方法を体系的に説明する。",
    why: "演習の背景にある考え方を理解したい人向け。101 題と併用",
    free: false,
    tags: ["論理", "論証", "批判", "理論"],
  },
  {
    id: "book-ronrigaku-noya",
    title: "論理学",
    kind: "book",
    author: "野矢茂樹（東京大学出版会）",
    domains: ["CODE"],
    subskills: ["design"],
    levelMin: 7,
    levelMax: 9,
    summary: "命題論理・述語論理を、記号を最小限にして「考え方」から説く大学向けの教科書。",
    why: "論理パズルの背後にある形式的な規則を学びたい人向け",
    free: false,
    tags: ["論理学", "命題論理", "述語論理", "大学"],
  },
  {
    id: "book-ronri-puzzle-dashikko",
    title: "論理パズル「出しっこ問題」傑作選",
    kind: "book",
    author: "小野田博一（講談社ブルーバックス）",
    domains: ["CODE"],
    subskills: ["design", "tracing"],
    levelMin: 4,
    levelMax: 7,
    summary: "正直者と嘘つき、帽子の色など、古典的な論理パズルを解説つきで楽しめる。",
    why: "Trivium の「論理パズル」タイプを伸ばしたい人向け。1 題ずつ場合分けを練習",
    free: false,
    tags: ["論理パズル", "場合分け", "嘘つき", "ブルーバックス"],
  },
  {
    id: "book-umigame-no-soup",
    title: "ポール・スローンのウミガメのスープ",
    kind: "book",
    author: "ポール・スローン・デス・マクヘール（エクスナレッジ）",
    domains: ["CODE", "READ"],
    subskills: ["design", "inference"],
    levelMin: 3,
    levelMax: 6,
    summary: "「はい／いいえ」の質問で状況を推理する水平思考パズルの定番。仮説を立てて検証する練習に。",
    why: "堅い論理より遊びから入りたい人向け。友人と出し合うと続く",
    free: false,
    tags: ["水平思考", "推理", "パズル", "遊び"],
  },
  {
    id: "book-sugaku-girl-baai-no-kazu",
    title: "数学ガールの秘密ノート／場合の数",
    kind: "book",
    author: "結城浩（SB クリエイティブ）",
    domains: ["CODE"],
    subskills: ["algorithms", "design"],
    levelMin: 5,
    levelMax: 7,
    summary: "対話形式で「数え上げ」の考え方を丁寧に追う。重複や漏れをなくす数え方が身につく。",
    why: "数的推理（場合の数）で数え漏れが出る人向け",
    free: false,
    tags: ["場合の数", "数学", "対話", "数的推理"],
  },
  {
    id: "course-khan-academy-ja",
    title: "カーンアカデミー（日本語）",
    kind: "course",
    author: "Khan Academy",
    url: "https://ja.khanacademy.org/",
    domains: ["CODE"],
    subskills: ["algorithms", "tracing"],
    levelMin: 2,
    levelMax: 7,
    summary: "算数・数学を動画と練習問題で無料で学べる。比・割合・確率など数的推理の基礎を復習できる。",
    why: "数的推理の土台（比・割合・平均）に不安がある人向け。無料で段階的",
    free: true,
    tags: ["数学", "算数", "動画", "無料", "数的推理"],
  },
  {
    id: "video-yobinori",
    title: "予備校のノリで学ぶ「大学の数学・物理」（YouTube）",
    kind: "video",
    author: "ヨビノリたくみ",
    url: "https://www.youtube.com/@yobinori",
    domains: ["CODE"],
    subskills: ["algorithms", "design"],
    levelMin: 5,
    levelMax: 9,
    summary: "高校〜大学の数学を授業形式で解説する人気チャンネル。確率・場合の数・論理の回もある。",
    why: "数学の考え方を授業として聞きたい人向け",
    free: true,
    tags: ["数学", "動画", "YouTube", "無料"],
  },

  // ------------------------------------------------------------------ 技術記事（LOGIC 中〜上級）
  {
    id: "web-qiita",
    title: "Qiita",
    kind: "web",
    author: "Qiita",
    url: "https://qiita.com/",
    domains: ["CODE", "WRITE"],
    subskills: ["design", "clarity"],
    levelMin: 4,
    levelMax: 8,
    summary: "エンジニアの技術記事共有サイト。Python の小技から設計の話まで幅広い。",
    why: "他人のコードと説明を読んで、自分でも技術記事を書いてみたい人向け（書く練習にもなる）",
    free: true,
    tags: ["技術記事", "Python", "アウトプット"],
  },
  {
    id: "web-zenn",
    title: "Zenn",
    kind: "web",
    author: "Zenn",
    url: "https://zenn.dev/",
    domains: ["CODE", "WRITE"],
    subskills: ["design", "structure"],
    levelMin: 4,
    levelMax: 8,
    summary: "エンジニア向けの記事・本の投稿サイト。体系的な「本」形式の無料コンテンツがある。",
    why: "1 つのテーマを本の形でまとまって読みたい人向け",
    free: true,
    tags: ["技術記事", "本", "アウトプット"],
  },
];

/** id で引く */
export function findMaterial(id: string): Material | undefined {
  return MATERIALS.find((m) => m.id === id);
}
